name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - saga

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ steps.web-app-deploy.outputs.web_app_url }}

    env:
      APP_REG_CLIENT_ID: ${{ secrets.APP_REG_CLIENT_ID }}
      LOCATION: northeurope
      APP_NAME: nrfassettrackerprod
      B2C_TENANT: nrfassettrackerprod

    if: secrets.E2E_AZURE_CREDENTIALS != ''

    steps:
      - uses: actions/checkout@v2
      - name: Determine Version
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          TAG=`git tag --contains ${{ github.sha }} | tr -d '\n'`
          VERSION=${TAG:-${{ github.sha }}}
          echo Version: ${VERSION}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Install Azures Functions CLI
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools-3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: az account list --output table
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit
      - run: npx tsc
      - run: |
          az deployment group create \
            --resource-group ${RESOURCE_GROUP:-nrfassettracker} \
            --mode Complete \
            --name cd-${{ env.VERSION }} \
            --template-file azuredeploy.json \
            --parameters \
              appName=${APP_NAME:-nrfassettracker} \
              location=$LOCATION \
              appRegistrationClientId=$APP_REG_CLIENT_ID \
              b2cTenant=${B2C_TENANT}
      - run:
          func azure functionapp publish ${APP_NAME:-nrfassettracker}api
          --typescript
      - name: Enable static site hosting for the app
        run:
          az storage blob service-properties update --auth-mode login
          --account-name ${APP_NAME:-nrfassettracker}app --static-website
          --404-document index.html --index-document index.html
      - name: Determine Web App settings
        run: node cli react-config >> $GITHUB_ENV
      - name: Build app
        id: web-app-deploy
        run: |
          echo Hosting at ${{ env.REACT_APP_WEB_APP_URL }}
          echo "::set-output name=web_app_url::${{ env.REACT_APP_WEB_APP_URL }}"
          export EXTEND_ESLINT=true
          OWNER=`echo $GITHUB_REPOSITORY | awk '{split($0,a,"/"); print a[1]}' | tr -d '\n'`
          git clone https://github.com/$OWNER/asset-tracker-cloud-app-js app
          cd app
          APP_TAG=`git tag --points-at HEAD | tr -d '\n'`
          APP_SHA=`git log -n 1 --pretty=format:"%H" | tr -d '\n'`
          export REACT_APP_VERSION=${APP_TAG:-${APP_SHA}}
          export PUBLIC_URL=${{ env.REACT_APP_WEB_APP_URL }}
          npm ci --no-audit
          npm run build
      - name: Publish app
        run: |
          export APP_STORAGE_CONNECTION_STRING=`az storage account show-connection-string --name ${APP_NAME:-nrfassettracker}app --query 'connectionString'` 
          az storage blob upload-batch --connection-string ${APP_STORAGE_CONNECTION_STRING} --account-name ${APP_NAME:-nrfassettracker}app -s ./app/build -d '$web'
