name: Publish Docker Image

on:
  push:
    branches:
      - saga
    paths:
      - Dockerfile
      - .github/workflows/publish-docker.yaml
  schedule:
    - cron: "0 0 * * *"

env:
  CR_PAT: ${{ secrets.CR_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Determine GitHub Container Registry repo name
        run: |
          DOCKER_REPO_NAME=`echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]'`
          echo "DOCKER_REPO_NAME=${DOCKER_REPO_NAME}" >> $GITHUB_ENV

      - name: Sign in to the GitHub Container Registry
        run: echo ${CR_PAT} | docker login ghcr.io -u USERNAME --password-stdin

      - run: docker build -t asset-tracker-cloud-azure .

      - run:
          docker tag asset-tracker-cloud-azure ghcr.io/${{ env.DOCKER_REPO_NAME
          }}-builder:saga

      - run: docker images

      - run: docker push ghcr.io/${{ env.DOCKER_REPO_NAME }}-builder:saga
