name: Publish Docker Image

on:
  push:
    branches:
      - saga
    paths:
      - Dockerfile
      - .github/workflows/publish-docker.yaml
  schedule:
    - cron: "0 0 * * *"

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build image
        run: |
          docker build -t bifravst/azure-dev .
      - name: Publish image
        run: |
          docker login -u bifravst -p $DOCKER_PASSWORD
          docker images
          docker push bifravst/azure-dev
