name: Publish Docker Image

on:
  push:
    branches:
      - saga
    paths:
      - Dockerfile
      - .github/workflows/publish-docker.yaml
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: saga
      - name: Inspect image
        run: |
          docker image inspect ${{ env.DOCKER_IMAGE }}
